### ISSUE TITLE
Typo - Chp 11, Sec 2, Figure 11.4: wrong threshold for p-value

### ISSUE THREAD

**Issue by rmorsomme** [OpenIntroStat/ims#259] opened 2022-06-15 16:23 UTC
- Chapter number: 11

- Section number: 2

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): Figure 11.4

- Original text: in Figure 11.4, only 2 points are identified as at least as extreme as the observed difference (0.292)

- Suggestion for corrected text: the 5 points on the right should be included; the caption should reflect also the change in p-value.

- Justification for suggestion: use the actual observed difference 21/24-14/24(=0.2916667) as the threshold instead of the rounded value 0.292.

**Comment by rmorsomme** [comment] 2022-06-15 16:34
The rest of the text should also be modified accordingly.
For instance, line 676 of the .rmd should read "in the sex discrimination study, the p-value was found to be approximately **0.05**".

**Comment by mine-cetinkaya-rundel** [comment] 2023-02-22 06:41
Duplicate of #243

**Closed by mine-cetinkaya-rundel** 2023-02-22 06:41 UTC
